spring:
  datasource:
    url: jdbc:mysql://localhost:3306/roadmap_db?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: root1234

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

server:
  port: 8080