spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/roadmap_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root1234

  jpa:
    hibernate:
      ddl-auto: update   # 애플리케이션 실행 시 테이블 생성 후 종료 시 삭제
    show-sql: true
    properties:
      hibernate:
        format_sql: true      # SQL을 보기 좋게 출력

server:
  port: 8080