version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: jido-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 980122
      MYSQL_DATABASE: LOADMAP_PROGRAM
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - jido-net

  app:
    container_name: jido-app
    build:
      context: .
      dockerfile: Dockerfile
    image: jido-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://jido-mysql:3306/LOADMAP_PROGRAM?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 980122
    networks:
      - jido-net

volumes:
  mysql_data:

networks:
  jido-net:
    driver: bridge