name: Deploy jido-backend-project

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build Spring Boot JAR
        run: ./gradlew clean build -x test

      # ✅ .env 파일을 먼저 생성한다
      - name: Create .env file from single GitHub Secret
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      # ✅ 그 다음 .env 포함해서 전체를 EC2로 전송
      - name: Copy project to EC2 (including .env)
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "."
          target: "/home/${{ secrets.EC2_USER }}/jido"

      - name: SSH into EC2 and run Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd jido
            docker compose down || true
            docker compose --env-file .env up -d --build